# NumPy
- Short for Numerical Python
- Foundational Package for Numerical computing in python
- Provides an ndarray object which is an efficient multidimensional array providing fast array oriented operations
- Provides a lot of functions

In [2]:
import numpy as np

# Creating ndarrays

##### Creating ndarray from an object

In [3]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [4]:
type(a1)

numpy.ndarray

In [5]:
t1 = (1,2,3,4,5)
a1 = np.array(t1)
a1

array([1, 2, 3, 4, 5])

In [6]:
a1 = np.array(range(1,11))
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a1.shape

(10,)

In [8]:
a1.dtype

dtype('int32')

In [9]:
a1.ndim

1

In [10]:
a1 = np.array([[1,2,3], [4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a1.shape

(2, 3)

In [12]:
a1.ndim

2

In [13]:
a1 = np.array([[[1,2],[3,4],[10,11]], [[5,6], [7,8], [12,13]]])
a1

array([[[ 1,  2],
        [ 3,  4],
        [10, 11]],

       [[ 5,  6],
        [ 7,  8],
        [12, 13]]])

In [14]:
a1.shape

(2, 3, 2)

In [15]:
a1.ndim

3

In [16]:
a = np.array([1,2,3,4,5], dtype = float)
a

array([1., 2., 3., 4., 5.])

In [17]:
a.dtype

dtype('float64')

In [18]:
a = np.array([1.5,2.6,3.1,4.8,5.2], dtype = int)
a

array([1, 2, 3, 4, 5])

In [19]:
a.dtype

dtype('int32')

### Typecasting ndarrays

In [20]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [21]:
a = a.astype(float)
a

array([1., 2., 3., 4., 5.])

In [22]:
a = a.astype(int)
a

array([1, 2, 3, 4, 5])

### Creating ndarrays by specifying a range

In [23]:
a1 = np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a1 = np.arange(0,21,2)
a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
a1 = np.arange(10)       # (0,10,1)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a1 = np.arange(10, dtype = float)
a1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Creating ndarrays of ones

In [27]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.ones((5,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### Creating ndarray of zeros

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Creating ndarray of a specific value

In [30]:
np.full((4,5), fill_value = 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### Creating an identity matrix

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# --------------------------------------------------------------------------------------
# Operations on ndarrays

In [32]:
a1 = np.array([1,2,3,4,5,6])
a1

array([1, 2, 3, 4, 5, 6])

In [33]:
# list
l = [1,2,3,4,5,6]
l + 2

TypeError: can only concatenate list (not "int") to list

In [ ]:
a1 + 2

In [ ]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]
l1 + l2         # concatenation

In [ ]:
a1 = np.array([1,2,3,4,5,6])             # Shapes must be same
a2 = np.array([4,5,6,7,8,9])

In [ ]:
a1 + a2

In [ ]:
a1 + [2,3,4,5,6,7]

In [ ]:
a1 - 2

In [ ]:
a1 - a2

In [ ]:
a1 * 2

In [ ]:
print(a1)
print(a2)

In [ ]:
a1 * a2

In [ ]:
a1 = np.array([2,4,6,8,10])
a1 / 2

In [ ]:
a1 / a2

In [ ]:
a1 // 2

In [ ]:
a1 // a2

In [ ]:
a1 % 3

In [ ]:
a1 ** 2

In [ ]:
a2 = np.array([2,3,4,5,6])
a1 ** a2

In [ ]:
a1

In [ ]:
2 / a1

In [ ]:
l1 = [1,2,3,4,5,6]
l1 < 4

In [ ]:
a1 = np.array([1,2,3,4,5,6])
a1 < 4

In [ ]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,7])

In [ ]:
a1 < a2

In [ ]:
a1 > a2

In [ ]:
a1 <= a2

In [ ]:
a1 == a2

In [ ]:
# Operation between two ndarrays is not possible if shapes are not same
a1 = np.array([1,2,3,4,5])
a2 = np.array([2,3,4,5,6,7])

a1 + a2

## Indexing and Slicing ndarrays

In [ ]:
a = np.arange(11,21)
a

In [ ]:
a[0]

In [ ]:
a[1]

In [ ]:
a[6]

In [ ]:
a[-1]

In [ ]:
a[-2]

In [ ]:
a[0:8]

In [ ]:
a[0:8:1]

In [ ]:
a[::]          # By default start = 0, end = len(a), step = 1

In [ ]:
a[-8:-3]

In [ ]:
a[::-1]

## Reshape and Transpose

In [ ]:
a = np.arange(16)
a

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
a = a.reshape((16,1))
a

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
a = a.reshape((1,16))
a

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
a.reshape((4,4))

In [ ]:
a.reshape((2,2,4))

In [ ]:
a = np.arange(36)
a.reshape((1,36))
a.reshape((2,18))
a.reshape((3,12))
a.reshape((4,9))
a.reshape((6,6))
a.reshape((9,4))
a.reshape((12,3))
a.reshape((18,2))
a.reshape((36,1))
print('Total possible 2d shapes : ', 9)

In [ ]:
a = np.arange(16).reshape((4,4))
a

In [ ]:
a.T

# ----------------------------------------------------------------------------------

# Functions

In [34]:
a = np.array([2,4,3,6,5,8,7,9,1,0])
a

array([2, 4, 3, 6, 5, 8, 7, 9, 1, 0])

In [35]:
a.sort()

In [36]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
s = np.square(a)
s

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [38]:
np.sqrt(s)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
a = np.array([8,27,64])
np.cbrt(a)

array([2., 3., 4.])

In [40]:
np.abs([-1,2,3,-5,-6,-2,6])

array([1, 2, 3, 5, 6, 2, 6])

In [41]:
np.abs([-2.5, 6.4, -3.8])

array([2.5, 6.4, 3.8])

In [45]:
np.add([1,2,3], [4,5,6])

array([5, 7, 9])

In [46]:
np.subtract([4,5,6], [1,2,3])

array([3, 3, 3])

In [47]:
np.multiply([1,2,3], [2,3,4])

array([ 2,  6, 12])

In [48]:
np.divide([4,2,6], [2,2,2])

array([2., 1., 3.])

In [49]:
a1 = np.array([2,1,4,5,3,6])
a2 = np.array([3,4,2,1,6,5])

In [50]:
np.maximum(a1, a2)

array([3, 4, 4, 5, 6, 6])

In [51]:
np.minimum(a1, a2)

array([2, 1, 2, 1, 3, 5])

In [52]:
np.greater(a1, a2)

array([False, False,  True,  True, False,  True])

In [53]:
np.less(a1, a2)

array([ True,  True, False, False,  True, False])

In [54]:
a1 = np.arange(21)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [55]:
np.mean(a1)

10.0

In [56]:
np.var(a1)

36.666666666666664

In [57]:
np.std(a1)

6.0553007081949835

In [58]:
a1.mean()

10.0

In [59]:
a1.std()

6.0553007081949835

In [60]:
a1.var()

36.666666666666664

In [61]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [63]:
a.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [64]:
a.min()

1

In [65]:
a.max()

10

In [66]:
a.sum()

55

In [71]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [72]:
a.shape

(8, 8)

In [73]:
a.mean()

31.5

In [74]:
a.mean(axis = 0)

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [75]:
a.mean(axis = 1)

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [76]:
a.std()

18.472953201911167

In [77]:
a.std(axis = 0)

array([18.33030278, 18.33030278, 18.33030278, 18.33030278, 18.33030278,
       18.33030278, 18.33030278, 18.33030278])

In [78]:
a.std(axis = 1)

array([2.29128785, 2.29128785, 2.29128785, 2.29128785, 2.29128785,
       2.29128785, 2.29128785, 2.29128785])

In [79]:
a.max(axis = 0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [80]:
a.max(axis = 1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [84]:
x = np.array([50,30,80,20,10,40])
x

array([50, 30, 80, 20, 10, 40])

In [85]:
np.argmax(x)

2

In [86]:
np.argmin(x)

4

In [87]:
np.max(x)

80

In [89]:
a1 = np.array([2,1,5,4,3,5,6,7,3,10,2,3]).reshape(3,4)
a1

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [90]:
a1.ravel()

array([ 2,  1,  5,  4,  3,  5,  6,  7,  3, 10,  2,  3])

In [91]:
a2 = a1.reshape(1,3,4)
a2

array([[[ 2,  1,  5,  4],
        [ 3,  5,  6,  7],
        [ 3, 10,  2,  3]]])

In [92]:
a2.shape

(1, 3, 4)

In [93]:
a2 = a2.squeeze()
a2

array([[ 2,  1,  5,  4],
       [ 3,  5,  6,  7],
       [ 3, 10,  2,  3]])

In [94]:
a2.shape

(3, 4)

In [98]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Concatenation

In [99]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

In [101]:
np.concatenate((a1,a2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [102]:
a1 = np.array([2,4,1,6,5,8]).reshape(2,3)
a1

array([[2, 4, 1],
       [6, 5, 8]])

In [103]:
a2 = np.array([5,2,6,9,1,4]).reshape(2,3)
a2

array([[5, 2, 6],
       [9, 1, 4]])

In [104]:
np.concatenate((a1,a2), axis = 0)

array([[2, 4, 1],
       [6, 5, 8],
       [5, 2, 6],
       [9, 1, 4]])

In [105]:
np.concatenate((a1,a2), axis = 1)

array([[2, 4, 1, 5, 2, 6],
       [6, 5, 8, 9, 1, 4]])

## Random numbers

In [125]:
np.random.randint(1,50)

6

In [119]:
np.random.randint(50)

48

In [134]:
np.random.randint(11,100,10)

array([57, 78, 20, 81, 85, 60, 86, 27, 19, 33])

In [137]:
np.random.randint(11,100, (10,10))

array([[79, 54, 81, 44, 90, 96, 16, 89, 67, 51],
       [96, 76, 56, 71, 52, 75, 54, 81, 35, 29],
       [81, 56, 19, 69, 28, 91, 39, 91, 87, 97],
       [94, 44, 70, 95, 31, 65, 27, 89, 29, 85],
       [39, 75, 21, 92, 58, 63, 56, 86, 77, 67],
       [59, 81, 77, 89, 58, 64, 73, 66, 14, 95],
       [62, 90, 27, 26, 20, 11, 86, 68, 45, 84],
       [29, 14, 23, 88, 59, 78, 61, 33, 75, 64],
       [48, 84, 88, 42, 62, 88, 49, 95, 49, 11],
       [60, 48, 51, 80, 97, 84, 77, 43, 50, 89]])

In [138]:
np.random.randn(10)

array([ 0.98502532, -0.62125305,  0.89281307, -1.65241048,  1.55960335,
        0.55708811,  0.55781383, -0.33486111,  0.77004013,  0.23862805])

In [139]:
np.random.randn(3,4)

array([[-1.27035597,  1.63614362,  0.04844228, -0.25484751],
       [-0.46448102,  1.48545304, -0.27698534, -1.32836221],
       [-1.44270861, -0.40310421, -0.56637515,  0.13606168]])

## Linear Algebra

In [140]:
a = np.array([4,3,7,9,2,3,9,6,1,4,7,6,11,4,8,7]).reshape((4,4))
a

array([[ 4,  3,  7,  9],
       [ 2,  3,  9,  6],
       [ 1,  4,  7,  6],
       [11,  4,  8,  7]])

In [141]:
from numpy.linalg import det
det(a)

527.0000000000006

In [142]:
from numpy.linalg import inv
inv(a)

array([[-0.0170778 , -0.02087287, -0.07969639,  0.10815939],
       [-0.22580645, -0.38709677,  0.61290323,  0.09677419],
       [-0.10436433,  0.31688805, -0.15370019, -0.0056926 ],
       [ 0.27514231, -0.10815939, -0.04933586, -0.07590133]])

In [144]:
from numpy.linalg import eig
eig(a)

(array([22.97864964,  3.76499269, -4.34011564, -1.40352668]),
 array([[-0.51289911, -0.39468612,  0.5270535 ,  0.05108621],
        [-0.41676444,  0.52758299,  0.07812217, -0.85784205],
        [-0.37954612,  0.5045306 ,  0.33673147,  0.494701  ],
        [-0.64744625, -0.55796767, -0.77635266, -0.12949184]]))

## Conditional Indexing

In [146]:
a = np.random.randint(11,100,(8,8))
a

array([[90, 55, 71, 98, 49, 34, 88, 47],
       [87, 21, 53, 74, 24, 52, 26, 35],
       [26, 47, 98, 30, 85, 23, 82, 34],
       [24, 58, 88, 44, 52, 60, 64, 63],
       [85, 82, 93, 64, 37, 72, 93, 73],
       [58, 51, 31, 88, 35, 69, 64, 28],
       [76, 95, 13, 80, 66, 64, 83, 30],
       [23, 42, 54, 64, 95, 28, 92, 61]])

In [147]:
a > 50

array([[ True,  True,  True,  True, False, False,  True, False],
       [ True, False,  True,  True, False,  True, False, False],
       [False, False,  True, False,  True, False,  True, False],
       [False,  True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True, False,  True, False,  True,  True, False],
       [ True,  True, False,  True,  True,  True,  True, False],
       [False, False,  True,  True,  True, False,  True,  True]])

In [148]:
a[a > 50]

array([90, 55, 71, 98, 88, 87, 53, 74, 52, 98, 85, 82, 58, 88, 52, 60, 64,
       63, 85, 82, 93, 64, 72, 93, 73, 58, 51, 88, 69, 64, 76, 95, 80, 66,
       64, 83, 54, 64, 95, 92, 61])

In [149]:
a[a < 50]

array([49, 34, 47, 21, 24, 26, 35, 26, 47, 30, 23, 34, 24, 44, 37, 31, 35,
       28, 13, 30, 23, 42, 28])

In [151]:
a[a <= 30]

array([21, 24, 26, 26, 30, 23, 24, 28, 13, 30, 23, 28])

In [152]:
a[a >= 70]

array([90, 71, 98, 88, 87, 74, 98, 85, 82, 88, 85, 82, 93, 72, 93, 73, 88,
       76, 95, 80, 83, 95, 92])

In [154]:
b = a[a >= 50]
b[b <= 60]

array([55, 53, 52, 58, 52, 60, 58, 51, 54])

## Slicing in Multidimensional Arrays

In [155]:
a = np.random.randint(10,100,(10,10))
a

array([[93, 26, 63, 14, 28, 58, 91, 96, 54, 12],
       [53, 93, 58, 53, 32, 36, 15, 28, 99, 13],
       [31, 64, 46, 62, 66, 13, 31, 90, 43, 12],
       [70, 64, 89, 67, 77, 13, 34, 54, 83, 81],
       [98, 58, 39, 20, 94, 78, 23, 91, 26, 39],
       [96, 17, 91, 69, 95, 88, 68, 97, 98, 30],
       [53, 54, 65, 85, 36, 22, 11, 55, 43, 75],
       [95, 51, 31, 50, 53, 51, 70, 64, 70, 27],
       [50, 39, 12, 31, 32, 99, 43, 36, 71, 16],
       [43, 52, 53, 78, 42, 99, 92, 63, 18, 25]])

In [156]:
a[0]

array([93, 26, 63, 14, 28, 58, 91, 96, 54, 12])

In [157]:
a[1]

array([53, 93, 58, 53, 32, 36, 15, 28, 99, 13])

In [158]:
a[0:4]

array([[93, 26, 63, 14, 28, 58, 91, 96, 54, 12],
       [53, 93, 58, 53, 32, 36, 15, 28, 99, 13],
       [31, 64, 46, 62, 66, 13, 31, 90, 43, 12],
       [70, 64, 89, 67, 77, 13, 34, 54, 83, 81]])

In [159]:
a[3:8]

array([[70, 64, 89, 67, 77, 13, 34, 54, 83, 81],
       [98, 58, 39, 20, 94, 78, 23, 91, 26, 39],
       [96, 17, 91, 69, 95, 88, 68, 97, 98, 30],
       [53, 54, 65, 85, 36, 22, 11, 55, 43, 75],
       [95, 51, 31, 50, 53, 51, 70, 64, 70, 27]])

In [163]:
a[0][4]

28

In [166]:
a[0:4 , 0:4]

array([[93, 26, 63, 14],
       [53, 93, 58, 53],
       [31, 64, 46, 62],
       [70, 64, 89, 67]])

In [167]:
a[2:7, 2:5]

array([[46, 62, 66],
       [89, 67, 77],
       [39, 20, 94],
       [91, 69, 95],
       [65, 85, 36]])